### ISSUE TITLE
Colorblind fixes needed

### ISSUE THREAD

**Issue by adavidw** [Anahkiasen/cookie-monster#1]
The green text used is too similar to the yellow text to be able to be distinguished by color blind people. An easy improvement that would help some people would be to darken the green, like to #00BB00. (I believe right now it's #00FF00). A better solution would be to provide some other visual indication or pick a different color entirely. I think best practice would be to find a color scheme that works for everyone, but if that's not possible, a color blind setting could be added that changes green to blue or something.

**Comment by adavidw** [comment]
The two parts of the interface where this is a problem are the bottom bar and the store. Green in other places is not really a problem since you're not trying to tell it apart from the yellow

**Comment by Anahkiasen** [comment]
Work on this has been started as you can see here https://github.com/Anahkiasen/cookie-monster/blob/master/src/cookie-monster.js#L56

I had already abstracted all the colors to variables to easily swap them in prevision of this. I added a `colorblind` option that switches what set of colors is used. I currently only changed the `green` the value it had in the original CM colorblind version, is any other color causing trouble ?
