### ISSUE TITLE
Calculations for portals is wrong in end game

### ISSUE THREAD

**Issue by kaiog** [Anahkiasen/cookie-monster#16]
Found on version 1.040.11.

I currently have all upgrades and cookie-monster does not see the correct increase for purchasing portals.

Cookie-monster says bonus income for my 176th portal is:
148.292 M
But it actually is:
703 841 114.4

It seems that some upgrade is not calculated correctly.

**Comment by Anahkiasen** [comment]
Yeah this should be fixed in the release to come, Cookie Monster for next version switched from custom calculations to a system where it simulates the buy and stores the actual bonus income that was obtained so it's more future-proof and exact.
