### ISSUE TITLE
Bonus income bugged

### ISSUE THREAD

**Issue by blue-river** [Anahkiasen/cookie-monster#2]
I just started using the newest version from this project and it says all buildings except antimatter condensers are far better than they really are. it estimates the bonus income for any building to be roughly 40B, compared to 57B for the antimatter condensers.

**Comment by Anahkiasen** [comment]
Can you try with the `develop` branch see if it's a bug that has been fixed in the meantime ? I seem to get the correct BI in local, but I'm not sure.

``` js
javascript: (function () {
  var jA = document.createElement('script');
  jA.setAttribute('type', 'text/javascript');
  jA.setAttribute('src', 'https://raw.github.com/Anahkiasen/cookie-monster/develop/dist/cookie-monster.min.js?' + new Date().getTime());

  document.body.appendChild(jA);
}());
```

**Comment by blue-river** [comment]
Same numbers show as far as I can see through the visual issues in the develop branch, unfortunately.

Here's some screenshots:
![bonus income](https://f.cloud.github.com/assets/1621888/1820133/ac4cd464-70d2-11e3-93b6-22ca0851ea9d.png)

**Comment by Anahkiasen** [comment]
Ok I'll take a look, can you export your save so I can debug this ?

**Comment by blue-river** [comment]
Of course, here it is:

MS4wNDAzfHwxMzg3NzM1MDE3OTY2O05hTjsxMzg4MzUzNzI0NTcxfDAxMTExMDAwfDUwNDU3NTcwOTM2NDkwNzUwMDsxMjg4NDE5NDc2NTY5Nzc4NDAwMDsyNDI4Mzs2Mzc5OzE5ODY1NDk4NzA3MTM1OTQyMDszNDU2ODstMTstMTsyODQxOTEwMjU5ODkzNjY4MjAwMDszOzExOzA7MDstMTs1OzQxNTs5NTg4Nzc4NjQ2NDI5NTI0MDA7MzcwOzE0OzI0M3wyNTksMjU5LDY0MzUwNTczNTE2NzEyLDA7MjQ5LDI0OSwxNzQ3OTU5Mzk1NDIwMjgsMDsyMjIsMjIyLDEwMTE1OTczMzQ2LDA7MjEwLDIxMCwyNjU1MDIxMjUxMiwwOzIwMSwyMDEsOTA2OTMyNjczNTEsMDsxOTEsMTkxLDIyMzM4OTAyMDM0MywwOzE3OSwxNzksODA2OTcxODYwMzk4LDA7MTc3LDE3NywxMzM2NzkxNTQ0NjE2MSwwOzE1MywxNTMsMTUxMDUyMzM4NzYwNzQ4LDA7MTQwLDE0MCwxNDE4NDE0NTczMTUyMTczLDA7fDQ1MDM1OTk2MjczNzA0OTU7NDUwMzU5OTYyNzM3MDQ5NTszMzc3Njk5NzIwNTI3ODcxOzQ1MDM1NzM4NDk4MzE5MzU7MjgxNDc0OTc2NzEwNjU1OTs0NTAzNDk2NTQ4MTU1MzkxOzk5NjQzMjQxMjY3MXw0NTAzNTk5NjI3MzcwNDk1OzIyNjA1MjcxODUxMzM1Njc7MTMxMDcx%21END%21

**Comment by Anahkiasen** [comment]
Ok I found why, will push a fix soon.

**Comment by Anahkiasen** [comment]
Should be fixed on master.

**Comment by blue-river** [comment]
Thanks for the quick fix :)
