### ISSUE TITLE
CM fails with opaque "these aren't the droids" error message

### ISSUE THREAD

**Issue by huttarl** [Anahkiasen/cookie-monster#36]
I'm new to CM and thought I'd give it a try.
I created a bookmarklet with the javascript code as described at http://cookieclicker.wikia.com/wiki/Cookie_Monster_%28JavaScript_Add-on%29#Bookmarklet.
I then went to the tab where I was playing CC (http://orteil.dashnet.org/cookieclicker/), and clicked on the new bookmarklet. I got a mysterious "These aren't the droids you're looking for" message. No clue whether that meant that my version of CC was too new for CM, or vice versa, or what. By looking at the minified CM source code it seems to have something to do with the document title (which in my case contains "Cookie Baker" but not "Cookie Clicker"), or more directly, it has to do with 0===this.$game.length.

I looked at the wiki page referenced above to find out whether CM is supposed to support CC classic, or the beta, or both, but I couldn't find that information.

**Comment by aeons** [comment]
Click the bookmarklet, then open a javascript console (F12 in Chrome) and paste and run these two lines:

```
CookieMonster.shouldRun = function(){ return true; };
CookieMonster.start();
```

This just bypasses that function, since the latest update renamed the window to Cookie Baker.

**Comment by aeons** [comment]
And it's back to being named Cookie Clicker, so disregard that comment :)

**Comment by huttarl** [comment]
OK. Any possibility of making the error message more indicative of what the problem is?

**Comment by davidgro** [comment]
> And it's back to being named Cookie Clicker, so disregard that comment :)

No, it's not. Not during Business Day anyway.  CM needs an update to fix this.

**Comment by Anahkiasen** [comment]
You can send a PR to modify the message if you want, it's a message from the original Cookie Monster

**Comment by davidgro** [comment]
@Anahkiasen Please see new issue #37.

**Comment by huttarl** [comment]
@Anahkiasen: In order to write a fix and send a pull request, I'd need to understand what the actual problem is (and it might be one of several different problems, depending on conditions). But in fact I don't know what problem causes this message.
