### ISSUE TITLE
Need private build documentation

### ISSUE THREAD

**Issue by davidgro** [Anahkiasen/cookie-monster#37]
Can someone please add documentation to the Readme about how to build and load a private copy of Cookie Monster? When it was all one file on Pastebin I had a private fork, but I don't know how to do that now.  

Even a simple change like adding '|| name == "Cookie Baker"' isn't something I would want to submit without the ability to test it! And I do want to contribute more than that (there are several fixes and features I think I could code myself if I could test them)

**Comment by Anahkiasen** [comment]
Did you check the README ? https://github.com/Anahkiasen/cookie-monster#contributing or do you have additional questions ?

**Comment by davidgro** [comment]
Yup. The big question is: After downloading the source, what needs to be
done in order to load it into Cookie Clicker in my browser?

**Comment by Anahkiasen** [comment]
You should be able to create the usual bookmarklet but that points to the file in local, per example :

``` js
javascript: (function () {  var jA = document.createElement('script');  jA.setAttribute('type', 'text/javascript');  jA.setAttribute('src', 'http://localhost/cookie-monster/dist/cookie-monster.js?' + new Date().getTime());  document.body.appendChild(jA);}());
```

**Comment by davidgro** [comment]
Great!  Thanks!
I had the impression that there was some kind of build process needed
(minifiying or something) before it could work.

EDIT: Oh, I see there is some stuff in the Readme that I missed before. Sorry about that.

**Comment by Anahkiasen** [comment]
Well you will need to run Grunt yeah

**Comment by davidgro** [comment]
When I get home today (or perhaps later this weekend) I will set up a fork and try to fix #36 as a trial run :-)
I will close this issue when I get set up.

**Comment by davidgro** [comment]
I am stuck. through trial and error I figured out extra packages that need to be installed (and how to do so, and I took notes so I can update the Readme) but now I am hitting this:

$ ./node_modules/.bin/grunt
Running "compass:compile" (compass) task
    error dist/sass/styles.scss (Line 21 of dist/sass/helpers/_variables.scss: Invalid CSS after "...reen : #76B7E1 ": expected "}", was "!global;")
overwrite styles.css 
    error dist/sass/colorblind.scss (Line 21 of dist/sass/helpers/_variables.scss: Invalid CSS after "...reen : #76B7E1 ": expected "}", was "!global;")
overwrite colorblind.css 
Compilation took 7.007s
Warning: ↑ Use --force to continue.

Aborted due to warnings.

Even if I knew CSS and could fix the source files, it still means something is working for you that isn't for me.  Any ideas?

**Comment by royaldark** [comment]
@davidgro: I had the same problem, but was able to solve it easily. !global is new to Sass 3.3, but the stable version of Compass uses Sass 3.2. To solve, you need to use the pre-release version of Compass.
`gem install compass --pre`

**Comment by davidgro** [comment]
Thanks!

**Comment by Anahkiasen** [comment]
I thought I had packed a Gemfile to install the proper gems but seems I forgot to commit it, will fix that later.
