### ISSUE TITLE
CM fails on new update

### ISSUE THREAD

**Issue by lordio** [Anahkiasen/cookie-monster#38]
Running the current version of CM on Clicker 1.0414 ("not fooling anyone") results in the cookie count not updating (even if the Short Numbers option is changed; it stays on the short scale). Numbers on buildings cycle as normal but do not update when clicked (neither cost nor count). Interestingly, with ROI/BCI enabled, the "best" building changes when a building is clicked. Also, the bottom bar keeps correct track of all its values, but also seems to believe no cookies are being generated ("Time Left" does not update).

Tooltips that normally pop up when hovering over clickable items do not appear.

**Comment by Kebabpizza** [comment]
Yeah, it is spitting errors.

Uncaught TypeError: Cannot read property 'style' of undefined main.js?v=1.516:2459
Game.tooltip.update main.js?v=1.516:2459
(anonymous function) cookie-monster.min.js?1396654557332:4
(anonymous function) VM1003:16
Game.Loop

**Comment by DosParkers** [comment]
Bug still here. Cookie Monster still unusable.
