### ISSUE TITLE
Game Stops When Cookie Monster Loads

### ISSUE THREAD

**Issue by skletzk** [Anahkiasen/cookie-monster#39]
As of 4/4/14, the game just completely stops when I load cookie monster. I'm running it in Chrome 33.0.1750.154 (currently up to date). Here's the error message from the console:

```
Uncaught TypeError: Cannot read property 'style' of undefined        main.js?v=1.517:2467
Game.tooltip.update        main.js?v=1.517:2467
(anonymous function)        cookie-monster.min.js?1396706053718:4
(anonymous function)        VM4550:16
Game.Loop        Game.Loop main.js?v=1.517:5345
```

**Comment by Kebabpizza** [comment]
See https://github.com/Anahkiasen/cookie-monster/issues/38

**Comment by davidschwegler** [comment]
I NEED MY COOKIE MONSTER D:

**Comment by studog-github** [comment]
+1
I saw the author responding to comments in the last few days, so hopefully an update is on its way.

**Comment by skletzk** [comment]
Sorry, I didn't read #38 carefully enough. Lemme see if I can close this as a duplicate.
