### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by lucabondi** [Anahkiasen/cookie-monster#4]
- Research Upgrades' Bonus Income that gives cookie production multiplier now shows NaN.
- Bonus Income of Buildings and Upgrades doesn't change during Frenzies or Clot.
- When a Golden Cookie gives Frenzy during a Clot, the Clot bar doesn't disappear

Thanks for the great work you're doing. 

EDIT: Another bug i just found... Bonus Income calculations for the Trilliion Fingers Upgrade is definitely wrong... it says  the BI is 8,192... here's a save so you can check.

MS4wNDAzfHwxMzg4NTkwNDAzNDk5O05hTjsxMzg4NTk3MDAyOTE3fDExMTExMTExfDI1ODA5MTkxODgyMTE2NjQuNTszMzgzODY1NDc3MDQ3ODczLjU7NTM3OTs2Njc2OzUxMzMwNzQ3NjkxNi42ODEzNDsxOTUzMTstMTstMTs1MjM1NjMxMTUxMzQ0MTcxMDAwMDsxOzA7MDswOy0xOzY7NDA7Mjk5MTU0MTU3NzY4MDAxLjk0OzA7MTM7NDF8MTIwLDEyMCw1Mjg1MTM3ODQsMDsxMzYsMTM2LDI4MzA0NzAxODg3LDA7ODQsODQsMTI3NTkwNDAsMDs3Miw3MiwyNjYzODQyOCwwOzY4LDY4LDg2Mzk4NzQzLDA7NjIsNjIsMTMwNjE3MzQ1LDA7NTksNTksNDQ2MjIwMzczLDA7NjMsNjMsODk1MjcwODc4NCwwOzQ2LDQ2LDcxMTk2MDg1MzM2LDA7MzcsMzcsNTE0NDk2NDEyOTI3LDA7fDQ1MDM1OTk2MjczNTQxMTE7NDUwMzE4NzMxMDUxMDA3OTsyMjY5MzkxOTk5NzI5NjM5OzM5NDA2NTI3ODYxNTM5ODM7MjQ0MDM2NjA2NDMxNTI5NTs0MjIyMDEyOTgyMDM0MDkxOzU4NDA0ODQ0MzM3MXw0NTAzNTk5NjI3MzcwNDk1OzIzOTI0Njg1ODI1NjM4Mzk7MTMxMDcx%21END%21

**Comment by Anahkiasen** [comment]
First two should be good on develop (not pushed yet). The third one I'm having trouble grasping it, the code doesn't even allow the user to have frenzies during the Grandmapocalypse, or do you mean blood frenzy ?

**Comment by Anahkiasen** [comment]
Ok no I see what you mean. Didn't remember that clots canceled Blood Frenzies and vice versa. Seems to be working in local, will wait a little to check some things before I push.

**Comment by aiviru** [comment]
You can get regular frenzies during clot too, in the transitional period between the Grandmapocalypse upgrades, or when you have a clot up when you cancel it out via a pledge. At a guess any event that can mess with the multiplier used by buffs should cancel out all the others.

Offtopic: Glad to see this getting some love, and it's very nice to see it improve pretty much daily.

**Comment by lucabondi** [comment]
I'm in the first phase of Grandmapocalypse (where i stop buying research upgrades), so i'm getting 66% Golden Cookies and 33% Wrath Cookies... it's actually a bad idea to click a golden cookie during a clot... 

About the Trillion Fingers... it happened the same with Quadrillion and Quintillion fingers... so there must be a wrong variable somewhere in that algorithm.

**Comment by Anahkiasen** [comment]
Yup it was the "x% for each cursor per non object" formula that was wrong. All the things mentioned in this thread should be fixed. Refresh the page to get the new update.

**Comment by lucabondi** [comment]
Yes, everything seems to work fine.

I might have another issue... but i need to check this first. I'll eventually open another thread.

**Comment by Anahkiasen** [comment]
Aaallrighty then
