### ISSUE TITLE
Error trying to run grunt - Invalid CSS after "...reen : #76B7E1 ": expected "}", was "!global;")

### ISSUE THREAD

**Issue by Qhorin** [Anahkiasen/cookie-monster#42]
When following the README directions to run grunt, I receive the following errors. I was wondering if anyone had run into this problem and solved it. I was hoping to help troubleshoot the most recent break involving tooltips. If this is not the proper place to bring up this problem, I apologize.

[USERNAME cookie-monster]$ ./node_modules/.bin/grunt
Running "compass:compile" (compass) task
    error dist/sass/styles.scss (Line 21 of dist/sass/helpers/_variables.scss: I                                                                                        nvalid CSS after "...reen : #76B7E1 ": expected "}", was "!global;")
identical styles.css
    error dist/sass/colorblind.scss (Line 21 of dist/sass/helpers/_variables.scs                                                                                        s: Invalid CSS after "...reen : #76B7E1 ": expected "}", was "!global;")
identical colorblind.css
Compilation took 0.724s
Warning: â Use --force to continue.

Aborted due to warnings.

**Comment by Anahkiasen** [comment]
Most likely you need to update your Sass version.

**Comment by Qhorin** [comment]
I'm using sass-3.2.19 with compass-0.12.5

Is 3.2.19 sufficient?

I tried updating sass to 3.3.5, but received an dependency error when running grunt. Compass needed sass 3.2.19. Any ideas?

**Comment by Anahkiasen** [comment]
Yeah the latest of both Sass and Compass were supposed to come out at the same time but there was a problem on Compass's end so now Sass 3.3 is out but not Compass 1.0 so you'll need to do `gem install compass --pre` to get the version of Compass that works with Sass 3.3

**Comment by Qhorin** [comment]
Thanks! `gem install compass --pre` worked for me.

Now I'm getting 5 errors while running the Grunt command. Are these a problem or ignorable?

```
Running "jshint:all" (jshint) task

   src/CookieMonster/automate/bank.js
     60 |CookieMonster.Automate.getBankValue = function(bank) {
                                                            ^ 'bank' is defined but never used.
   src/CookieMonster/interface/buff-bars.js
    170 | if (Game.season != "christmas" && name === 'seasonPopup') {
                            ^ Expected '!==' and instead saw '!='.
    214 | if (Game.season != "christmas" && name === 'seasonPopup') {
                            ^ Expected '!==' and instead saw '!='.
   src/CookieMonster/interface/tooltips.js
    171 |  yMax = $(window).height() - $(tooltip).outerHeight(); // window size - tooltip size
                                         ^ 'tooltip' is not defined.
    179 | $(tooltipAnchor).offset({
            ^ 'tooltipAnchor' is not defined.

>> 5 errors in 33 files
```

Full output can be found here: http://pastebin.com/bCCrgG2B

**Comment by Anahkiasen** [comment]
No you can ignore them, they're warnings of coding styles.
