### ISSUE TITLE
Upgrade tooltip does not update after purchasing a upgrade

### ISSUE THREAD

**Issue by domisum** [Anahkiasen/cookie-monster#57]
Before purchasing the "Specialized Chocolate Chips" the tooltip shows the information about them, just how it is supposed to be. (http://puu.sh/k4E2n/9d0f64bf49.jpg) After purchasing the upgrade (left-click) the tooltip is not updated and stil shows the "Specialized Chocolate Chips" although it should show the tooltip for the grandma-upgrade. (http://puu.sh/k4E4l/22f621739a.jpg) The tooltip is not updated when moving the mouse without leaving the icon, but shows the proper tooltip after leaving the icon and reentering it.

Maybe this helps: After creating a screenshot with the screencapper "puush" by using the Ctrl + Shift + 2 shortcut the tooltip updated.

**Comment by Anahkiasen** [comment]
Unfortunately Cookie Monster is not maintained anymore, you should try [Cookie Master](https://github.com/greenc/CookieMaster/tree/master) (although it hasn't been updated in a while but, well, Cookie Clicker itself either so)
