### ISSUE TITLE
Cookie Clicker updated to v2.0042

### ISSUE THREAD

**Issue by ghost** [Anahkiasen/cookie-monster#58]
Lots of changes including a whole new building:
- new building : Chancemakers
- new milk, new kittens, new dragon aura, new cookie, new upgrade tier
- buffs no longer affect offline CpS
- Godzamok's hunger was made less potent (this is a nerf, very sorry)
- grimoire spell costs and maximum magic work differently
- Spontaneous Edifice has been reworked
- changed unlock levels and prices for some cursor upgrades
- fixed buggy pantheon slots, hopefully
- fixed "Legacy started a long while ago" showing as "a few seconds ago"
- Cookie Clicker just turned 4. Thank you for sticking with us this long!

**Comment by Anahkiasen** [comment]
Hi! this version is not maintained anymore unfortunately, you can find the current active fork of CM over here https://github.com/Aktanusa/CookieMonster doesn't work yet with the latest new stuff but it's fairly quick to be updated usually
