### ISSUE TITLE
Cookie Monster Menu

### ISSUE THREAD

**Issue by Bzzz** [Anahkiasen/cookie-monster#9]
Hi,
for various reasons I'm using Firefox 15, and there is no menu for the Cookie Monster. Everything else works fine, but I cannot access these settings. Any ideas on this?

**Comment by Anahkiasen** [comment]
The Cookie Monster settings appear in Menu, do they not appear there ? If not, can you check Firefox's console see if any error is in there ?

**Comment by Bzzz** [comment]
===navigating to Cookie Clicker===
Timestamp: 08.01.2014 23:48:58
Warning: Unknown property 'user-select'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/style.css?v=1.5070
Line: 61

Timestamp: 08.01.2014 23:48:58
Warning: Unknown property 'transition'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/style.css?v=1.5070
Line: 583

Timestamp: 08.01.2014 23:48:58
Warning: Unknown property 'transition'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/style.css?v=1.5070
Line: 845

Timestamp: 08.01.2014 23:48:58
Warning: Unknown property 'transition'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/style.css?v=1.5070
Line: 868

Timestamp: 08.01.2014 23:48:59
Error: The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must to be declared in the document or in the transfer protocol.
Source File: http://orteil.dashnet.org/cookieclicker/
Line: 0

Timestamp: 08.01.2014 23:48:59
Warning: Use of Mutation Events is deprecated. Use MutationObserver instead.
Source File: chrome://ghostery/content/ghostery.js
Line: 396

===launching Cookie Monster===
Timestamp: 08.01.2014 23:50:00
Warning: Unknown property 'box-sizing'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/
Line: 0

Timestamp: 08.01.2014 23:50:00
Warning: Unknown property 'box-sizing'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/
Line: 0

Timestamp: 08.01.2014 23:50:00
Warning: Unknown property 'box-sizing'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/
Line: 0

Timestamp: 08.01.2014 23:50:01
Warning: Unknown property 'user-select'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/
Line: 0

Timestamp: 08.01.2014 23:50:01
Warning: Error in parsing value for 'background'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/
Line: 0

Timestamp: 08.01.2014 23:50:01
Warning: Error in parsing value for 'background'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/
Line: 0

Timestamp: 08.01.2014 23:50:01
Warning: Error in parsing value for 'background'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/
Line: 0

Timestamp: 08.01.2014 23:50:01
Warning: Error in parsing value for 'background'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/
Line: 0

Timestamp: 08.01.2014 23:50:01
Warning: Error in parsing value for 'background'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/
Line: 0

Timestamp: 08.01.2014 23:50:01
Warning: Error in parsing value for 'filter'.  Declaration dropped.
Source File: http://orteil.dashnet.org/cookieclicker/
Line: 0

There are no additional errors when clicking the Menu page. And yes, there is no CM submenu there, as it would be using for example Opera. Just nothing after the last CC button and text.

**Comment by Anahkiasen** [comment]
What browser/OS are you on?

**Comment by Bzzz** [comment]
firefox:amd64/raring 15.0.1+build1-0ubuntu2
running Kubuntu 13.10 @ kernel 3.11.0-14-generic

**Comment by Anahkiasen** [comment]
Wait... Firefox **15** ? Latest is 26, that's 11 versions late or is that the latest on Kubuntu ?

**Comment by Bzzz** [comment]
As said in very first post...

**Comment by 0x3D** [comment]
He's using Firefox 15 for various reasons.
IIRC kubuntu is ubuntu with kde(Linux!). And if I again remember correctly Firefox for Linux uses the same versioning as Windows uses.

Can someone confirm it works in Firefox 26.0? 
If it does then probably close at wontfix.

**Comment by Bzzz** [comment]
Very helpful indeed. Wontfix because Wedontcare?

**Comment by 0x3D** [comment]
Wontfix because it takes time to develop against a legacy version.
Fix it yourself?
Try to understand man.
1. Download, install and update? kubuntu 13.10
2. Download and install a legacy version of Firefox (15.0) 
3. Set up a development environment.
4. Fix the issue by probably removing things Firefox implemented in the 11 versions that has passed.

That is a lot of work to make sure 1 user can keep using his outdated browser.
How do you even dare to visit websites when your browser is that out of date?

**Comment by Bzzz** [comment]
1. No need to, also affects windows versions
2. Replace with the version you like: https://download.mozilla.org/?product=firefox-15.0&os=win&lang=en-US
3. You have to do that for any new FF version as well? Or is this just generic, so it doesn't have to do anything with firefox?
4. FF15 doesn't work, FF16 doesn't work, FF17 works. So the change was made between 16.0 and 17.0 code. Maybe because of changes for the second ESR version, but that's just a guess.

I will keep my outdated browser, as long as the newer version-inflated crap won't work as well as 15 does. Sad, but true. I (have to...) work with newer versions at work and at university, and I cannot spot ANY improvement in ANY way. It's just larger, slower, it is missing functions (or needs addons to bring them back in an unstable way) and it blows up its version number every week. Hipsterlicious.

**Comment by Bzzz** [comment]
You know what...the guy from CookieMaster is able to create a settings page that actually works. Furthermore, don't ask me what's causing this, but running CC in the background now really saves CPU load. And also watching it doesn't max out one core, so no more lag, no more fan action, just having a quiet, passive cooled system. 

So...it's a no-brainer for me, I'll switch to the better plugin. Cya!

**Comment by Anahkiasen** [comment]
You do know I'm not paid to do this ? That I have my day jobs and several open source packages I have to maintain and that this is just an additional thing I do in my spare time. No need to be rude.
